### ISSUE TITLE
Issue with hostnames and graph display using ui-graphite2 

### ISSUE THREAD

**Issue by vatese** [shinken-monitoring/mod-ui-graphite#14]
Hello!

After fixing some issued I had with ui-graphite2 I noticed something. My hostnames for the servers I am checking with shinknen are currently in the form hostname.domain.com. When graphite sends the metrics to the storage directory, the dots are being replaced by underscores. When ui-graphite2 forms the uri, the underscores are not converted and the uri includes dots again, which generates an internal server error when making the links to the graphs. I noticed this issue as the servers that do not include dots in their names load their graphs correctly. Do you have any suggestions to work around this bug (and which .py files are involved in generating the uri)? (This issue was not present with the previous version of ui-graphite)

**Comment by vatese** [comment]
I came up with a rudimentary solution. I changed line 187 of util.py to:

```
graphite_metric = GraphiteMetric(self.prefix, self.hostname.replace(".","_"),
                                              self.cfg.graphite_data_source, 
                                              self.servicename, metric['name'], self.postfix)

 # Original:
 # Graph main series
          #  graphite_metric = GraphiteMetric(self.prefix, self.hostname,
          #                                   self.cfg.graphite_data_source,
          #                                   self.servicename, metric['name'], self.postfix)
```

This will only work if the graphite module replaces the dots with underscores when creating the metrics at the specified storage location.

**Comment by mohierf** [comment]
Indeed the problem comes from the host_name (and service_description) that should not be normalized as the metrics are ... I will push a fix for this!

The module `graphite` only allows [a-zA-Z0-9_-] in the host_name and service_description and it substitutes any other character in the host name with an `_`, but the module `ui-graphite` does not filter the dot character !

**Comment by mohierf** [comment]
@vatese : the fix you applied and the one I just commited has the same result ... you may keep your modification ot, If you prefer, apply mine.

**Comment by vatese** [comment]
Thanks so much! I will move to your solution, it is way more sophisticated. Regards!

**Comment by fakhruddinhamid** [comment]
Thanks for fixing this, I was beating my head for the same bug.
When do you think this would be available via shinken install ? as currently I am in process of writing chef cookbook to setup the shinken cluster from scratch and for now I have just copied the solution in the test cluster.

**Comment by mohierf** [comment]
I just published both modules on shinken.io ... if you `shinken search graphite` you will see the new versions (graphite2, 2.1.3 and ui-graphite2, 2.1.2)
