### ISSUE TITLE
Issue with generated url using ui-graphite2

### ISSUE THREAD

**Issue by claneys** [shinken-monitoring/mod-ui-graphite#15]
Hi,

I got an issue using webui2 with ui-graphite2, graph image generated is like : 

```
http://10.145.7.7:7767/graph?url=http%3A//10.145.7.7/render/%3Fwidth%3D786%26height%3D308%26fontSize%3D10%26lineMode%3Dconnected%26from%3D13%3A14_20151230%26until%3D17%3A14_20151230%26tz%3DEurope/Paris%26title%3Dlocalhost/%20-%20time%26target%3Dalias%28color%28localhost.time%2C%22green%22%29%2C%22time%22%29%26target%3Dalias%28color%28constantLine%283%29%2C%22blue%22%29%2C%22Max%22%29
```

Then there isn't graph displayed, only a broken link to it. Is it normal or do I make something wrong ?

Thanks

**Comment by mohierf** [comment]
You URL seems ok to me ... do you still have this problem?

**Comment by claneys** [comment]
Yes, with lastest firefox version.

**Comment by claneys** [comment]
Do you need a trace or something ?

**Comment by mohierf** [comment]
If you get the content of the `url` parameter and use it as an URL in your browser, do you have a graph ?

**Comment by claneys** [comment]
Not until i translate every ascii code to there character. But yes.

**Comment by mohierf** [comment]
Ok. So it should be ok also in WebUI2 ...

Do you have the most recent versions of WebUI2 and UI-Graphite2 ?

Is it the same for all the graphs ?

**Comment by claneys** [comment]
Yes, and I got these modules using shinken cli install command.

**Comment by mohierf** [comment]
I just made a test with the most recent versions of those modules and I did not have any problem ...

Except for the servers URL

My graph URL is: `http://graphite.com/render/?width=586&height=308&fontSize=10&lineMode=connected&from=09:29_20160106&until=13:29_20160106&tz=Europe/Paris&title=cogny/nrpe-IO - tps&target=alias(color(knm.servers.cogny.shinken.nrpe-IO.tps,"green"),"tps")`

And my request is: `http://shinken.com:7767/graph?url=http%3A//graphite.com/render/%3Fwidth%3D586%26height%3D308%26fontSize%3D10%26lineMode%3Dconnected%26from%3D09%3A29_20160106%26until%3D13%3A29_20160106%26tz%3DEurope/Paris%26title%3Dcogny/nrpe-IO%20-%20tps%26target%3Dalias%28color%28knm.servers.cogny.shinken.nrpe-IO.tps%2C%22green%22%29%2C%22tps%22%29`

Should you copy yours ? You can easily catch the URL parameter with Chrome/Firefox F12 ...

**Comment by claneys** [comment]
I use F12 into firefox and i got a 404 error about that url : 
`http://10.145.7.7:7767/graph?url=http%3A//10.145.7.7/render/%3Fwidth%3D786%26height%3D308%26fontSize%3D10%26lineMode%3Dconnected%26from%3D22%3A22_20160106%26until%3D02%3A22_20160107%26tz%3DEurope/Paris%26title%3Dlocalhost/Root_Partition%20-%20/%26target%3Dalias%28color%28localhost.Root_Partition._%2C%22green%22%29%2C%22/%22%29%26target%3Dalias%28color%28constantLine%2833252%29%2C%22orange%22%29%2C%22Warning%22%29%26target%3Dalias%28color%28constantLine%2833257%29%2C%22red%22%29%2C%22Critical%22%29%26target%3Dalias%28color%28constantLine%2833262%29%2C%22blue%22%29%2C%22Max%22%29"`

And about some js script not found : 

```
"NetworkError: 404 Not Found - http://10.145.7.7:7767/static/availability/js/justgage.js"
justgage.js
"NetworkError: 404 Not Found - http://10.145.7.7:7767/static/availability/js/raphael.2.1.0.min.js"
raphael....min.js
"NetworkError: 404 Not Found - http://10.145.7.7:7767/static/availability/js/justgage.js"
justgage.js
"NetworkError: 404 Not Found - http://10.145.7.7:7767/static/availability/js/raphael.2.1.0.min.js"
```

How did you get the graph url ? From a browser, i see the request but not the other one.

**Comment by mohierf** [comment]
If you have those errors about JS files I will suspect that you do not have the most recent version of WebUI2 ... what is your version ? You can get it in the UI if you click on the top left Shinken logo ... the most recent one is 2.2.1

**Comment by claneys** [comment]
I got the 2.2.1

**Comment by claneys** [comment]
Problem was missing python module requests ( and arrow btw)

**Comment by floppy84** [comment]
Hi,

I decided to test the new webui and new graphite module.
All seems to work, but the graphe display don't.

I got an issue on graph view.
I can't see graph in webui2.

i got this message : Error: 404 Not Found

Sorry, the requested URL 'http://s06-mgt-shinken-1.neopost.grp:7767/graph?url=10.207.100.236%3A8080/render/%3Fwidth%3D786%26height%3D308%26fontSize%3D10%26lineMode%3Dconnected%26from%3D07%3A46_20160303%26until%3D11%3A46_20160303%26tz%3DEurope/Paris%26title%3DS06-GBZMON179/%20-%20rta%26target%3Dalias%28color%28S06-GBZMON179.rta%2C%22green%22%29%2C%22rta%22%29%26target%3Dalias%28color%28constantLine%281000%29%2C%22orange%22%29%2C%22Warning%22%29%26target%3Dalias%28color%28constantLine%283000%29%2C%22red%22%29%2C%22Critical%22%29' caused an error:

No connection adapters were found for '10.207.100.236:8080/render/?width=786&height=308&fontSize=10&lineMode=connected&from=07:46_20160303&until=11:46_20160303&tz=Europe/Paris&title=S06-GBZMON179/ - rta&target=alias(color(S06-GBZMON179.rta,"green"),"rta")&target=alias(color(constantLine(1000),"orange"),"Warning")&target=alias(color(constantLine(3000),"red"),"Critical")'

regards

**Comment by floppy84** [comment]
Ok i change the URI parameter on module ui-graphite to http://10.207.100.236:8080

and now it seems to be better but i got message : : 

**Image not found**

`
[1457003142] ERROR: [broker-master] [WebUI-graph] Image URL not found: http://10.207.100.236:8080/render/?width=786&height=308&fontSize=10&lineMode=connected&from=08:05_20160303&until=12:05_20160303&tz=Europe/Paris&title=S06-GBZMON179/ - rta&target=alias(color(S06-GBZMON179.rta,"green"),"rta")&target=alias(color(constantLine(1000),"orange"),"Warning")&target=alias(color(constantLine(3000),"red"),"Critical")
[1457003142] ERROR: [broker-master] [WebUI-graph] Image URL not found: http://10.207.100.236:8080/render/?width=786&height=308&fontSize=10&lineMode=connected&from=08:05_20160303&until=12:05_20160303&tz=Europe/Paris&title=S06-GBZMON179/ - pl&target=alias(color(S06-GBZMON179.pl,"green"),"pl")&target=alias(color(constantLine(100),"orange"),"Warning")&target=alias(color(constantLine(100),"red"),"Critical")&target=alias(color(constantLine(100),"blue"),"Max")`

**Comment by floppy84** [comment]
Ok so i don't know why, but now i just have services graphe that work fine.
But for host i don't have graph
