### ISSUE TITLE
Misleading HTTP error and message: "Unauthorized" becomes "Not found"

### ISSUE THREAD

**Issue by soujak** [shinken-monitoring/mod-ui-graphite#17]
If the module internally fails to load Graphite images with HTTP 401 "Unauthorized" error, then in pages like `/host/$HOST` or `/service/$HOST/$SERVICE`, requests for image resources underURLs like `/graph?url=$GRAPHITEURL` fail as expected. Unfortunately they raise a wrong and misleading errors -- Shinken webui return a 404 "Not found" error, providing the additional message "image not found".

I think the HTTP error or at least the explicating message should be set more appropriately.

**Comment by mohierf** [comment]
As far as I understand, the problem is in the Shinken WebUI not in this module ... the Shinken WebUI raises a 404 error if the image cannot be fetched from Graphite, whatever the reason.
