### ISSUE TITLE
Malformed Graphite metrics path when using hosts variables

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-ui-graphite#3]
I defined an host variable as is : 
```
	_GRAPHITE_PRE			knm-rd.kiosks.IPM.RD
```
and the graphite path in WebUI is set as : 
```
knm-rd_kiosks_IPM_RD.Nadege-0001.shinken.__HOST__.rtmin
```

Note that dots (.) have been replaced with underscores (_). It is really not the desired result because dots are meaningful for Graphite counters organization.

I will propose a fix.

**Comment by Simage** [comment]
>My idea should be to use hostgroup in Graphite metric path. If an host is a member of the group named 'servers', the hostgroup name should be used as root in Graphite metric path. What do you think about it ?

What if a host is a member of multiple hostgroups?

**Comment by mohierf** [comment]
I finally implemented a new _GRAPHITE_GROUP host variable to deal with a sub level in Graphite hierarchy
